#Worksheet - 0

#Basics

##Exercise on Functions

###Task - 1

In [20]:
def lengthConversion():
  """
    used to convert m to ft or vice versa
  """
  length = input("Enter m or ft.")
  if(length == "m"):
    meter = float(input("Enter length in meter"))
    print(f"{meter}m = {meter * 3.28}ft.")
  elif(length == "ft"):
    feet = float(input("Enter length in feet"))
    print(f"{feet}ft = {feet / 3.28}m")
  else:
    raise ValueError("Invalid Length")
def weightConversion():
  '''
    used to convert kg to lbs or vice versa
  '''
  weight = input("Enter kg or lbs: ")
  if(weight == "kg"):
    kg = float(input("Enter weight in kg: "))
    print(f"{kg}kg => {kg * 2.20}lbs")
  elif(weight == "lbs"):
    lbs = float(input("Enter weight in lbs: "))
    print(f"{lbs}lbs => {lbs / 2.20}kg")
  else:
    raise ValueError("Invalid Weight")
def volumeConversion():
  '''
    used to convert litre to gallon or vice versa
  '''
  volume = input("Enter l or gal: ")
  if(volume == "l"):
    litre = float(input("Enter Litres: "))
    print(f"{litre}l => {litre * 0.264}gallons")
  elif(volume == "gal"):
    gal = float(input("Enter Gallon: "))
    print(f"{gal}gallons => {gal / 0.264}litres")
  else:
    raise ValueError("Invalid Unit")

In [21]:

while True:
  typeOfConv = input("Choose type of Conversion (length or weight or volume): ")
  try:
    if(typeOfConv == "length"):
      lengthConversion()
    elif(typeOfConv == "weight"):
      weightConversion()
    elif(typeOfConv == "volume"):
      volumeConversion()
    if(typeOfConv in ["length", "weight", "volume"]):
      break;
    else:
      print("Invalid Input!!!(Enter: length or weight or volume)")
      continue;
  except ValueError as ve:
    print(f"Error: {ve}")
    continue;



Choose type of Conversion (length or weight or volume): length
Enter m or ft.m
Enter length in meterdf
Error: could not convert string to float: 'df'
Choose type of Conversion (length or weight or volume): length
Enter m or ft.m
Enter length in meter39
39.0m = 127.91999999999999ft.


###Task - 2

In [25]:
def sumIt(nums):
  summ = 0
  for i in nums:
    summ += i
  return summ
def avgIt(nums):
  summ = sumIt(nums)
  return summ/len(nums)

def maxIt(nums):
  max = nums[0]
  for i in nums:
    if i > max:
      max = i
  return max

def minIt(nums):
  min = nums[0]
  for i in nums:
    if i < min:
      min = i
  return min

In [30]:
while True:
    task = input("Choose an task (sum, average, max, min): ").strip().lower()

    try:
        if task not in ["sum", "average", "max", "min"]:
            print("Invalid Input!!! (Enter: sum, average, max, min)")
            continue

        nums = input("Enter a list of numbers separated by spaces: ").strip().split()
        nums = [float(num) for num in nums]

        if len(nums) == 0:
            raise ValueError("The list cannot be empty.")

        if task == "sum":
            result = sumIt(nums)
        elif task == "average":
            result = avgIt(nums)
        elif task == "max":
            result = maxIt(nums)
        elif task == "min":
            result = minIt(nums)

        print(f"The result of {task} task is: {result}")
        break

    except ValueError as ve:
        print(f"Error: {ve} Numeric Values only")
        continue

Choose an task (sum, average, max, min): min
Enter a list of numbers separated by spaces: 2 3 4 4 5 0
The result of min task is: 0.0


##Exercise on List Manipulation

In [39]:
def extract(nums):
    """1. Extracts every other value of list"""
    return nums[::2]

def slicee(nums, start, end):
    """2. Slice the list from start to end index"""
    return nums[start:end+1]

def reverse(nums):
    """3. reverses the list"""
    return nums[::-1]

def remove(nums):
    """4. Removes the first and last numbers of the list"""
    return nums[1:-1]

def getfirstn(nums, n):
    """5. Gets the first n number of items from the list"""
    return nums[:n]

def getlastn(nums, n):
    """6. Gets the last n number of items from the list """
    return nums[-n:]

def reverseskip(nums):
  """7. """
  return nums[-2::-2]

In [40]:
while True:
    task = input("Choose a task (extract, slice, reverse, remove, getfirstn, getlastn, reverseskip): ").strip().lower()

    try:
        if task not in ["extract", "slice", "reverse", "remove", "getfirstn", "getlastn", "reverseskip"]:
            print("Invalid Input!!! (Enter: extract, slice, reverse, remove, getfirstn, getlastn, reverseskip)")
            continue

        nums = input("Enter a list of numbers separated by spaces: ").strip().split()
        nums = [float(num) for num in nums]

        if len(nums) == 0:
            raise ValueError("The list cannot be empty.")

        if task == "extract":
            result = extract(nums)
        elif task == "slice":
            start = int(input("Enter start index: "))
            end = int(input("Enter end index: "))
            result = slice(nums, start, end)
        elif task == "reverse":
            result = reverse(nums)
        elif task == "remove":
            result = remove(nums)
        elif task == "getfirstn":
            n = int(input("Enter N: "))
            result = getfirstn(nums, n)
        elif task == "getlastn":
            n = int(input("Enter N: "))
            result = getlastn(nums, n)
        elif task == "reverseskip":
            result = reverseskip(nums)

        print(f"The result of {task} task is: {result}")
        break

    except ValueError as ve:
        print(f"Error: {ve}. Please enter valid numeric values.")
        continue

Choose a task (extract, slice, reverse, remove, getfirstn, getlastn, reverseskip): reverseskip
Enter a list of numbers separated by spaces: 1 2 3 4 5 6 7
The result of reverseskip task is: [6.0, 4.0, 2.0]


##Exercise on Nested List

In [42]:
def flatten(lst):
    """It makes a nested list into a single list(makes it into a single dimension)"""
    flat_list = []
    for sublist in lst:
        if isinstance(sublist, list):
            flat_list.extend(flatten(sublist))
        else:
            flat_list.append(sublist)
    return flat_list

def accessnestedelement(lst, indices):
    """Access the Nested List elements"""
    element = lst
    for index in indices:
        element = element[index]
    return element

def sumnested(lst):
    """Sums all the elements of the nested List"""
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sumnested(item)
        else:
            total += item
    return total

def removeelement(lst, elem):
    """Removes specific element of the list"""
    modified_list = []
    for item in lst:
        if isinstance(item, list):
            modified_list.append(removeelement(item, elem))
        elif item != elem:
            modified_list.append(item)
    return [sublist for sublist in modified_list if sublist]

def findmax(lst):
    """Finds the maximum value element of the list"""
    max_value = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_value = max(max_value, findmax(item))
        else:
            max_value = max(max_value, item)
    return max_value

def countoccurrences(lst, elem):
    """Count the number of time an element appears in the list"""
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += countoccurrences(item, elem)
        elif item == elem:
            count += 1
    return count

def flatten2(lst):
    """ """
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(flatten2(item))
        else:
            flat_list.append(item)
    return flat_list

def averagenested(lst):
    """ """
    flat_list = flatten(lst)
    return sum(flat_list) / len(flat_list) if flat_list else 0

In [44]:
while True:
    task = input("Choose a task (flatten, accessnestedelement, sumnested, removeelement, findmax, countoccurrences, flatten2, averagenested): ").strip().lower()

    try:
        if task not in ["flatten", "accessnestedelement", "sumnested", "removeelement", "findmax", "countoccurrences", "flatten2", "averagenested"]:
            print("Invalid Input!!! Please choose a valid task.")
            continue

        nested_list = eval(input("Enter a nested list (use square brackets []): "))  # Using eval to accept nested lists

        if not isinstance(nested_list, list):
            raise ValueError("Input must be a list")

        if task == "flatten":
            result = flatten(nested_list)
        elif task == "accessnestedelement":
            indices = list(map(int, input("Enter indices separated by spaces: ").strip().split()))
            result = accessnestedelement(nested_list, indices)
        elif task == "sumnested":
            result = sumnested(nested_list)
        elif task == "removeelement":
            elem = eval(input("Enter element to remove: "))  # Using eval to accept numbers and strings
            result = removeelement(nested_list, elem)
        elif task == "findmax":
            result = findmax(nested_list)
        elif task == "countoccurrences":
            elem = eval(input("Enter element to count: "))
            result = countoccurrences(nested_list, elem)
        elif task == "flatten2":
            result = flatten2(nested_list)
        elif task == "averagenested":
            result = averagenested(nested_list)

        print(f"The result of {task} task is: {result}")
        break

    except (ValueError, TypeError, IndexError) as e:
        print(f"Error: {e}. Please enter valid input.")
        continue

Choose a task (flatten, accessnestedelement, sumnested, removeelement, findmax, countoccurrences, flatten2, averagenested): flatten
Enter a nested list (use square brackets []): [[1, 3, 4 ,5, 6], [2]]
The result of flatten task is: [1, 3, 4, 5, 6, 2]


#Numpy

##Importing Necessary Libraries

In [ ]:
import numpy as np
import time

##Problem - 1: Array Creation

###1. Initializing Empty Array (2 * 2)

In [ ]:
array = np.empty((2, 2))
array #contains garbage values

array([[1.86792e-316, 0.00000e+000],
       [0.00000e+000, 5.78551e-321]])

In [ ]:
array = np.zeros((2, 2))
array #initializes with 0

array([[0., 0.],
       [0., 0.]])

In [ ]:
array = np.full((2, 2), 20) #you can specify your initialization value
array #20

array([[20, 20],
       [20, 20]])

###2. Initializing all one array (4 * 2)

In [ ]:
array = np.ones((4, 2), dtype=int) #set type to integer initiall float
array

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
array = np.full((4, 2), 1)
array

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

###3. New Array of Given Shape and type filled with fill value

In [ ]:
array = np.full((4, 4), 9, dtype=int)
array

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

###4. New array of zeros with same shape and type as given array

In [ ]:
array = np.full((4, 4), 8)
new_array = np.zeros_like(array)
new_array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

###5. New array of ones with same shape and type as given array

In [ ]:
array = np.full((4, 3), 8)
new_array = np.ones_like(array)
new_array

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

###6. Convert to NumPy array

In [ ]:
new_list = [1, 2, 3, 4]
np_list = np.array(new_list)
print("Normal List: ", new_list)
print("Numpy List: ", np_list)

Normal List:  [1, 2, 3, 4]
Numpy List:  [1 2 3 4]


##Problem - 2: Array Manipulation: Numerical Ranges and Array Indexing

###1. Create an array with values ranging from 10 to 49

In [ ]:
array = np.arange(10, 50)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

###2. Create a 3X3 matrix with values ranging from 0 to 8

In [ ]:
array = np.arange(0, 9)
reshaped = np.reshape(array, (3, 3))
print(array)
print(reshaped)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


###3. Create a 3*3 identity matrix

In [ ]:
array = np.eye(3, dtype=int)
array

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

###4. Random Array Size 30 and Mean

In [ ]:
random_arr = np.random.random(30)

mean_arr = random_arr.mean()

print(random_arr)
print("Mean: ", mean_arr)

[0.93134961 0.8635721  0.74932934 0.66765332 0.52366252 0.1321128
 0.24830668 0.73411917 0.33334322 0.83842636 0.58497043 0.28381651
 0.97193311 0.3997206  0.42720709 0.04949679 0.61037031 0.55043134
 0.56454661 0.03048991 0.73490457 0.0966294  0.19834246 0.32923038
 0.87757202 0.2289481  0.05639096 0.63524893 0.42955544 0.59497382]
Mean:  0.4892217964721296


###5. Create a 10X10 array with random values and find the minimum and maximum values

In [ ]:
# random_arr = np.random.random((10, 10))
random_arr = np.random.randint(1, 10, (10, 10))
min = random_arr.min()
max = random_arr.max()

print(random_arr)
print()
print("Min: ", min)
print("Max: ", max)

[[2 3 5 2 2 6 5 9 1 6]
 [5 4 2 7 8 9 3 1 5 2]
 [4 1 6 1 5 6 1 2 8 9]
 [7 7 6 8 7 5 6 8 5 2]
 [3 6 1 7 9 5 3 8 9 9]
 [8 1 9 5 8 8 5 1 3 6]
 [6 7 4 4 9 4 9 6 4 8]
 [9 8 9 7 9 3 4 8 5 4]
 [2 4 9 4 1 4 8 1 3 6]
 [9 4 1 1 3 9 8 4 5 9]]

Min:  1
Max:  9


###6. Create a zero array of size 10 and replace 5th element with 1

In [ ]:
array = np.zeros(10, dtype=int)
print(array)
array[4] = 1
print(array)

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0]


###7. Reverse an array

In [ ]:
array = [1 , 2, 0, 0, 4, 0]
rev_arr = array[::-1]
rev_arr

[0, 4, 0, 0, 2, 1]

###8. Create a 2d array with 1 on border and 0 inside

In [ ]:
arr = np.random.randint(1, 10, (7, 7))

# arr = np.zeros_like(arr)
arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1

arr[0:-1, 1:-1] = 0

arr

array([[1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1]])

###9. Create a 8X8 matrix and fill it with a checkerboard pattern

In [ ]:
array = np.zeros((9, 9), dtype=int)

array[1::2, 0::2] = 1
array[::2, 1::2] = 1
array

array([[0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0]])

##Problem - 3: Array Operations

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

###1. Add Arrays

In [ ]:
sum = x + y
sum1 = v + w
print(sum)
print()
print(sum1)

[[ 6  8]
 [10 13]]

[20 22]


###2. Subtract Arrays

In [ ]:
sub = x - y
sub1 = v - w
print(sub)
print()
print(sub1)

[[-4 -4]
 [-4 -3]]

[-2 -2]


###3. Multiply Array With Integer

In [ ]:
mulArr = 7 * x
mulArr

array([[ 7, 14],
       [21, 35]])

###4. Square of Each Element of Array

In [ ]:
powArr = x ** 2
powArr

array([[ 1,  4],
       [ 9, 25]])

###5. Dot Product

In [ ]:
vDotw = np.dot(v, w)
xDotv = np.dot(x, v)
xDoty = np.dot(x, y)

print(f"V.W: {vDotw}")
print(f"X.V: {xDotv}")
print(f"X.Y: \n{xDoty}")

V.W: 219
X.V: [29 77]
X.Y: 
[[19 22]
 [50 58]]


###6. Concatenate - 1

In [ ]:
conxy = np.concatenate((x, y), axis = 0)
convw = np.vstack((v, w))
print(conxy)
print()
print(convw)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]

[[ 9 10]
 [11 12]]


###7. Concatenate - 2 (Dimension Mismatch)

In [ ]:
conxv = np.concatenate((x, v), axis = 0)
conxv
##This cause error because the arrays should have the same number of dimensions
#x is a 2D array where as v is a 1D array

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

##Problem - 4: Matrix Operations

In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

###1. A.A^-1 = I

In [ ]:
A_Inverse = np.linalg.inv(A)
proof = np.round(np.matmul(A, A_Inverse))
proof

array([[1., 0.],
       [0., 1.]])

###2. AB != BA

In [ ]:
AB = np.matmul(A, B)
BA = np.matmul(B, A)

print(f"AB:\n{AB} \nBA:\n{BA}")

AB:
[[23 13]
 [51 29]] 
BA:
[[36 44]
 [13 16]]


###3. (AB)T = BT.AT

In [ ]:
AB = np.matmul(A, B)
AB_T = AB.T
B_T = B.T
A_T = A.T
B_T_Dot_A_T = np.matmul(B_T, A_T)

print(f"AB_T: \n{AB_T} \n\n B_T.A_T: \n{B_T_Dot_A_T}")

AB_T: 
[[23 51]
 [13 29]] 

 B_T.A_T: 
[[23 51]
 [13 29]]


###Linear Equation Using Inverse Method

In [ ]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1,  -1]])
B = np.array([-1, -3, 9])

A_Inverse = np.linalg.inv(A)

X = np.matmul(A_Inverse, B)

print(f"[x y z] = {X}")

[x y z] = [ 2.  1. -2.]


##Numpy Speed

In [ ]:
size = 1000000
matrices = 1000

pyArr1 = list(range(size))
pyArr2 = list(range(size))

npArr1 = np.arange(size)
npArr2 = np.arange(size)

sTime = time.time()
pySum = [pyArr1[i] + pyArr2[i] for i in range(size)]
pyTimeAdd = time.time() - sTime

sTime = time.time()
npSum = npArr1 + npArr2
npTimeAdd = time.time() - sTime

print(f"Addition Time: \nNumpy: {npTimeAdd:.5f} \nNormal Py list: {pyTimeAdd:.5f}\n")

sTime = time.time()
pyMul = [pyArr1[i] * pyArr2[i] for i in range(size)]
pyTimeMul = time.time() - sTime

sTime = time.time()
npMul = npArr1 * npArr2
npTimeMul = time.time() - sTime

print(f"Element Multiplication Time: \nNumpy: {npTimeMul:.5f} \nNormal Py list: {pyTimeMul:.5f}\n")

sTime = time.time()
pyDot = sum(pyArr1[i] * pyArr2[i] for i in range(size))
pyTimeDot = time.time() - sTime

sTime = time.time()
npDot = np.dot(npArr1, npArr2)
npTimeDot = time.time() - sTime

print(f"Dot Product Time: \nNumpy: {npTimeDot:.5f} \nNormal Py list: {pyTimeDot:.5f}\n")

pyMat1 = [[j for j in range(matrices)] for i in range(matrices)]
pyMat2 = [[j for j in range(matrices)] for i in range(matrices)]

npMat1 = np.arange(matrices**2).reshape(matrices, matrices)
npMat2 = np.arange(matrices**2).reshape(matrices, matrices)

sTime = time.time()
pyMatMul = [[sum(pyMat1[i][k] * pyMat2[k][j] for k in range(matrices)) for j in range(matrices)] for i in range(matrices)]
pyTimeMatMul = time.time() - sTime

sTime = time.time()
npMatMul = np.dot(npMat1, npMat2)
npTimeMatMul = time.time() - sTime

print(f"Matrix Multiplication Time: \nNumpy: {npTimeMatMul:.5f} \nNormal Py list: {pyTimeMatMul:.5f}\n")


Addition Time: 
Numpy: 0.00473 
Normal Py list: 0.08615

Element Multiplication Time: 
Numpy: 0.00275 
Normal Py list: 0.12858

Dot Product Time: 
Numpy: 0.00185 
Normal Py list: 0.09987

Matrix Multiplication Time: 
Numpy: 1.35412 
Normal Py list: 185.17150

